// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbX2RfjiLksDhsGlve93pF6Qh0Xul5TyI',
    appId: '1:414176863917:web:33aa158dae9aa70da40824',
    messagingSenderId: '414176863917',
    projectId: 'silaan',
    authDomain: 'silaan.firebaseapp.com',
    storageBucket: 'silaan.appspot.com',
    measurementId: 'G-XVRMKT6XXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKQiddPUpuxVE7UMiLgVvdWlyK5vZJ0s',
    appId: '1:414176863917:android:93423d8246c78d5fa40824',
    messagingSenderId: '414176863917',
    projectId: 'silaan',
    storageBucket: 'silaan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFDoQ2X5l-5rNjziPwMZVO_TsG7mYc1Pg',
    appId: '1:414176863917:ios:a023ef4084ea77cda40824',
    messagingSenderId: '414176863917',
    projectId: 'silaan',
    storageBucket: 'silaan.appspot.com',
    androidClientId: '414176863917-92ehi2h26u1eams5ovaf2in03j23bati.apps.googleusercontent.com',
    iosClientId: '414176863917-tht6kci66m41i6mie3r5lf6gc28edd4c.apps.googleusercontent.com',
    iosBundleId: 'com.elysian.autoqr',
  );
}
